FROM ubuntu:24.04

ENV DEBIAN_FRONTEND=noninteractive

WORKDIR /minecraft

RUN apt-get update && apt-get install -y \
    openjdk-8-jdk \
    && rm -rf /var/lib/apt/lists/*

COPY server-rl-craft/ /minecraft/
# If you have a backup of your world, copy it here. WSL command: kubectl cp namespace/podname:/minecraft/world /mnt/c/Minecraft/world-backup
# COPY world-backup/ /minecraft/world/

RUN echo "eula=true" > eula.txt

# with 4 players not more than 6GB RAM is used, 8GB should be enough
EXPOSE 25565
ENTRYPOINT [ "java" ] 
CMD ["-Xms4G", "-Xmx8G", "-jar", "forge-1.12.2-14.23.5.2860.jar", "nogui" ]